### ISSUE TITLE
Output file size

### ISSUE THREAD

**Issue by daviscodesbugs** [albarji/neural-style-docker#5]
Couldn't seem to find parameters for output file size. Is it a limitation of the algorithm itself? I would think that it could at least match the size of the input images.

**Comment by albarji** [comment]
Output file size is set to the default of neural-style, which is 500 pixels in the longest dimension (either rows or columns). It is possible to produce larger images by invoking the neural-style main directly, check:

`nvidia-docker run --rm albarji/neural-style -h`

And you will see there is a parameter just for that. This parameter, however, is not ported to the variants.sh fake-it.sh scripts.

Be advised though that large output images mean more GPU memory consumption. You might need a high-end GPU to produce images in the order of 1000x1000 px.

**Comment by wboykinm** [comment]
I'm late to the party to mention this, but after extensive testing last fall I found that the maximum output size I could get without a crash was 1280x1280 even using a p2.8xlarge instance. 

The quest for high-resolution continues 😁

**Comment by albarji** [comment]
That's a quite good resolution! My current preferred method is to generate a 500x500 image and then run Waifu2x (https://github.com/nagadomi/waifu2x) twice to perform super-resolution up to 2000x2000. It's far from perfect but for some styles works nicely.

I have also tried tiling the image into 3x3 or 5x5 pieces and running the method on each tile. This produces bad results (as expected) as when joining all tiles they don't really fit neatly and the borders between tiles stand out too much. I tried some ideas to smooth out this effect, but no luck so far.

**Comment by wboykinm** [comment]
@albarji I've actually had really good results tiling with [this imagemagick-based strategy](https://github.com/wboykinm/neural-style-docker/blob/master/scripts/neural-tile.sh) from @ProGamerGov. I keep meaning to try the Waifu2x method but I suspect upscaling wouldn't fly [with satellite imagery](http://planet.geosprocket.com/)

**Comment by albarji** [comment]
@wboykinm I've been away from this project for some time, but finally had the chance to try the tiling strategy you suggested, and it indeed works pretty well!

I'm now working in dockerizing an alternative, faster method for style transfer (https://github.com/rtqichen/style-swap). I might include this tiling method to produce larger images as well.

**Comment by wboykinm** [comment]
@albarji That's great news! Thanks for looking!

**Comment by albarji** [comment]
I just released a new 2.1 version which implements the tiling strategy, generalized to work at any target resolution. It also includes the style-swap algorithm I was dockerizing in the other repository linked above. So now you can generate high-res images fast!

**Comment by wboykinm** [comment]
@albarji 

![thanks](https://media.giphy.com/media/CYfzqCRbZCMEg/giphy.gif)
